import Header from "@/components/header";
import "./globals.css";
import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import Providers from "@/lib/providers";

const gro = Space_Grotesk({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ashwin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${gro.className}  text-black bg-gray-100 dark:text-white dark:bg-dark`}
      >
        <Providers>
          <Header />
          <main>{children}</main>
        </Providers>
      </body>
    </html>
  );
}
