import Header from "@/components/header";
import "./globals.css";
import type { Metadata } from "next";
import { Inter, Space_Grotesk } from "next/font/google";
import Providers from "@/lib/providers";
import MobileHeader from "@/components/mobile-nav";
import HomeSection from "@/components/home/home-section";

const gro = Inter({ subsets: ["cyrillic-ext"] });

export const metadata: Metadata = {
  title: "Ashwin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${gro.className} flex  w-full text-black/90 bg-light dark:text-beige dark:bg-dark`}
      >
        <Providers>
          <Header />
          <MobileHeader />

          <main className="w-full flex flex-col items-center justify-center  px-4 min-h-screen  ">
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
